export let mode = ["Standard"];
export let topic = ["Geography"];
export let questions = [
  ["What is the capital of France?", "Paris", "Lyon", "Marseille", "Nice"],
  [
    "What is the capital of Germany?",
    "Berlin",
    "Munich",
    "Frankfurt",
    "Hamburg",
  ],
  ["What is the capital of Italy?", "Rome", "Milan", "Naples", "Turin"],
  [
    "What is the capital of Spain?",
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
  ],
  [
    "What is the capital of the United Kingdom?",
    "London",
    "Manchester",
    "Birmingham",
    "Liverpool",
  ],
  [
    "What is the capital of the United States?",
    "Washington, D.C.",
    "New York",
    "Los Angeles",
    "Chicago",
  ],
  [
    "What is the capital of Canada?",
    "Ottawa",
    "Toronto",
    "Vancouver",
    "Montreal",
  ],
  [
    "What is the capital of Australia?",
    "Canberra",
    "Sydney",
    "Melbourne",
    "Brisbane",
  ],
  ["What is the capital of Japan?", "Tokyo", "Osaka", "Kyoto", "Nagoya"],
  [
    "What is the capital of China?",
    "Beijing",
    "Shanghai",
    "Guangzhou",
    "Shenzhen",
  ],
  [
    "What is the capital of Russia?",
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
  ],
  [
    "What is the capital of Brazil?",
    "Brasília",
    "Rio de Janeiro",
    "São Paulo",
    "Salvador",
  ],
  [
    "What is the capital of India?",
    "New Delhi",
    "Mumbai",
    "Bangalore",
    "Chennai",
  ],
  [
    "What is the capital of South Africa?",
    "Pretoria",
    "Cape Town",
    "Johannesburg",
    "Durban",
  ],
  ["What is the capital of Egypt?", "Cairo", "Alexandria", "Giza", "Luxor"],
  ["What is the capital of Nigeria?", "Abuja", "Lagos", "Kano", "Ibadan"],
  ["What is the capital of Kenya?", "Nairobi", "Mombasa", "Kisumu", "Nakuru"],
  [
    "What is the capital of Mexico?",
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
  ],
  [
    "What is the capital of Argentina?",
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
  ],
  [
    "What is the capital of Chile?",
    "Santiago",
    "Valparaíso",
    "Concepción",
    "La Serena",
  ],
  ["What is the capital of Peru?", "Lima", "Arequipa", "Cusco", "Trujillo"],
  [
    "What is the capital of Colombia?",
    "Bogotá",
    "Medellín",
    "Cali",
    "Barranquilla",
  ],
  [
    "What is the capital of Venezuela?",
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
  ],
  [
    "What is the capital of Saudi Arabia?",
    "Riyadh",
    "Jeddah",
    "Mecca",
    "Medina",
  ],
];
